version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: agendamento-de-veiculos
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
volumes:
  postgres_data: